name: workout_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Charts and data visualization
  fl_chart: ^0.69.0

  # Calendar and date/time utilities
  table_calendar: ^3.1.2
  intl: ^0.19.0

  # UI enhancements
  animated_bottom_navigation_bar: ^1.4.0
  percent_indicator: ^4.2.5
  dotted_dashed_line: ^0.0.3
  simple_animation_progress_bar: ^1.9.2
  animated_toggle_switch: ^0.8.5

  # State management and utilities
  provider: ^6.1.2

  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.2.3
  firebase_analytics: ^11.3.3

  # Additional utilities
  uuid: ^4.5.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/