// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlxhaaiY3wedGyliEBh83HKMskNcsc5ow',
    appId: '1:58848350275:android:605cd0d0abf6098b7844f6',
    messagingSenderId: '58848350275',
    projectId: 'work-out-45ccb',
    storageBucket: 'work-out-45ccb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiEK7sdSpLWtxHw6oWdtUpg7PpX1wT5xc',
    appId: '1:58848350275:ios:7c58984fcc1e52c57844f6',
    messagingSenderId: '58848350275',
    projectId: 'work-out-45ccb',
    storageBucket: 'work-out-45ccb.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnu4w9DH8GoL1C9VWtg5dJnJsl_h8pmUM',
    appId: '1:58848350275:web:33ff0dcb5faa82cc7844f6',
    messagingSenderId: '58848350275',
    projectId: 'work-out-45ccb',
    authDomain: 'work-out-45ccb.firebaseapp.com',
    storageBucket: 'work-out-45ccb.firebasestorage.app',
    measurementId: 'G-XXDQP27WPR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiEK7sdSpLWtxHw6oWdtUpg7PpX1wT5xc',
    appId: '1:58848350275:ios:b6780c31516b768c7844f6',
    messagingSenderId: '58848350275',
    projectId: 'work-out-45ccb',
    storageBucket: 'work-out-45ccb.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnu4w9DH8GoL1C9VWtg5dJnJsl_h8pmUM',
    appId: '1:58848350275:web:d97723621f4717ea7844f6',
    messagingSenderId: '58848350275',
    projectId: 'work-out-45ccb',
    authDomain: 'work-out-45ccb.firebaseapp.com',
    storageBucket: 'work-out-45ccb.firebasestorage.app',
    measurementId: 'G-3SF2ZBQK3Q',
  );

}